"""System-wide constants for AFS Acquisition."""

# Recording
MAX_WRITE_QUEUE_SIZE = 800
MAX_PROCESS_QUEUE_SIZE = 800
BATCH_SIZE = 20
MAX_SUB_BATCH = 10
TARGET_CHUNK_MB = 3
FLUSH_INTERVAL_SEC = 15.0
WRITE_TIMEOUT_SEC = 10.0
FRAME_TIMEOUT_MS = 30
RECORDING_COMPRESSION_LEVEL = 0
POST_COMPRESSION_LEVEL = 4
MIN_DISK_SPACE_MB = 50

# Display
LIVE_DISPLAY_FPS = 15
MIN_DISPLAY_INTERVAL = 1.0 / 15.0
STATUS_UPDATE_INTERVAL = 0.5

# Camera
DEFAULT_QUEUE_SIZE = 1
RECORDING_QUEUE_SIZE = 10
FRAME_POOL_SIZE = 10
MAX_FPS = 120
TARGET_RECORDING_FPS = 50

# GPU (optimized for i7-14700 with 20 cores)
GPU_BUFFER_POOL_SIZE = 8
GPU_BATCH_SIZE = 8

# Hardware
MAX_CONNECT_RETRIES = 3
CONNECT_RETRY_DELAY = 1.0
HEALTH_CHECK_INTERVAL = 5.0
VISA_TIMEOUT_MS = 5000

# Validation
MIN_FREQUENCY_MHZ = 0.001
MAX_FREQUENCY_MHZ = 30.0
MIN_AMPLITUDE_VPP = 0.002
MAX_AMPLITUDE_VPP = 20.0
MIN_STAGE_POSITION_UM = 0
MAX_STAGE_POSITION_UM = 25000

# Files
HDF5_EXTENSION = '.hdf5'
LOG_EXTENSION = '.log'
CONFIG_EXTENSION = '.json'
MAX_BACKUP_FILES = 3
